name: clang-tidy check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          apk update
          apk add clang20-extra-tools

      - name: Run clang-tidy
        run: |
          find . -name "*.c" -exec clang-tidy {} \; 