name: Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    strategy:
      matrix:
        include:
          - tool: cppcheck
            package: cppcheck
          - tool: clang-tidy
            package: clang20-extra-tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ${{ matrix.tool }}
        run: |
          apk update
          apk add ${{ matrix.package }}

      - name: Run ${{ matrix.tool }}
        run: |
          find . -name "*.c" -exec ${{ matrix.tool }} {} \; 